# This is a basic workflow to help you get started with Actions
            - نام: محیط Setup Node.js
  موارد استفاده: actions/setup-node@v3.9.1
  با:
    # همیشه تأیید اعتبار را در npmrc تنظیم کنید.
    همیشه-auth: # اختیاری، پیش‌فرض نادرست است
    # مشخصات نسخه نسخه مورد استفاده. مثال‌ها: 12.x، 10.15.1، >=10.15.0.
    node-version: # اختیاری
    # فایل حاوی مشخصات نسخه نسخه مورد استفاده. مثال‌ها: .nvmrc، .node-version، .tool-versions.
    node-version-file: # اختیاری
    # معماری هدف برای استفاده Node. مثال‌ها: x86، x64. به طور پیش فرض از معماری سیستم استفاده می کند.
    معماری: # اختیاری
    # اگر می‌خواهید اکشن آخرین نسخه موجود را که مشخصات نسخه را برآورده می‌کند بررسی کند، این گزینه را تنظیم کنید.
    بررسی آخرین: # اختیاری
    # رجیستری اختیاری برای تنظیم برای احراز هویت. رجیستری را در یک فایل سطح پروژه .npmrc و yarnrc. تنظیم می کند و auth را برای خواندن از env.NODE_AUTH_TOKEN تنظیم می کند.
    registry-url: # اختیاری
    # محدوده اختیاری برای احراز هویت در برابر رجیستری های محدوده. هنگام استفاده از رجیستری بسته های GitHub (https://npm.pkg.github.com/) به مالک مخزن باز می گردد.
    دامنه: # اختیاری
    # برای بیرون کشیدن توزیع های گره از نسخه های گره استفاده می شود. از آنجایی که یک پیش‌فرض وجود دارد، این معمولاً توسط کاربر ارائه نمی‌شود. هنگام اجرای این عمل در github.com، مقدار پیش فرض کافی است. هنگامی که در GHES اجرا می‌کنید، اگر با محدودیت نرخ مواجه هستید، می‌توانید یک نشانه دسترسی شخصی برای github.com ارسال کنید.
    نشانه: # اختیاری، پیش‌فرض ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # برای تعیین یک مدیر بسته برای ذخیره سازی در فهرست پیش فرض استفاده می شود. مقادیر پشتیبانی شده: npm، نخ، pnpm.
    حافظه پنهان: # اختیاری
    # برای تعیین مسیر فایل وابستگی استفاده می‌شود: package-lock.json، yarn.lock، و غیره.
    cache-dependency-path: # اختیاری
          
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
